s:Ge/World/Type = "TsCylinder"
s:Ge/World/Material = "G4_AIR"
d:Ge/World/RMax = 790.0 mm
d:Ge/World/HL = 1348.1 mm
d:Ge/World/TransX = 0 mm
d:Ge/World/TransY = 0 mm
d:Ge/World/TransZ = 0 mm
d:Ge/World/RotX = 0 deg
d:Ge/World/RotY = 0 deg
d:Ge/World/RotZ = 0 deg
sc:Ge/World/DrawingStyle = "WireFrame"
sc:Ge/World/Color = "white"
s:Ge/FieldContainer/Type = "TsCylinder"
s:Ge/FieldContainer/Parent = "World"
s:Ge/FieldContainer/Material = Ge/World/Material
d:Ge/FieldContainer/RMax = 790.0 mm
d:Ge/FieldContainer/HL = 1348.1 mm
d:Ge/FieldContainer/TransX = 0 mm
d:Ge/FieldContainer/TransY = 0 mm
d:Ge/FieldContainer/TransZ = 0 mm
d:Ge/FieldContainer/RotX = 0 deg
d:Ge/FieldContainer/RotY = 0 deg
d:Ge/FieldContainer/RotZ = 0 deg
sc:Ge/FieldContainer/Color = "grey220"
sc:Ge/FieldContainer/DrawingStyle = "WireFrame"
s:Ge/FaradayCup/Type = "Group"
s:Ge/FaradayCup/Parent = "FieldContainer"
d:Ge/FaradayCup/TransX = 0 mm
d:Ge/FaradayCup/TransY = 0 mm
d:Ge/FaradayCup/TransZ = 0 mm
d:Ge/FaradayCup/RotX = 0 deg
d:Ge/FaradayCup/RotY = 0 deg
d:Ge/FaradayCup/RotZ = 0 deg
s:Ge/VacuumWindow/Type = "TsCylinder"
s:Ge/VacuumWindow/Parent = "FaradayCup"
s:Ge/VacuumWindow/Material = "Aluminum"
d:Ge/VacuumWindow/RMax = 71.5 mm
d:Ge/VacuumWindow/HL = 0.05 mm
d:Ge/VacuumWindow/TransX = 0 mm
d:Ge/VacuumWindow/TransY = 0 mm
d:Ge/VacuumWindow/TransZ = -0.05 mm
d:Ge/VacuumWindow/RotX = 0 deg
d:Ge/VacuumWindow/RotY = 0 deg
d:Ge/VacuumWindow/RotZ = 0 deg
sc:Ge/VacuumWindow/Color = "grey220"
sc:Ge/VacuumWindow/DrawingStyle = "Solid"
s:Ge/Vacuum/Type = "TsCylinder"
s:Ge/Vacuum/Parent = "FaradayCup"
s:Ge/Vacuum/Material = "FCVacuum"
sv:Ma/FCVacuum/Components = 4 "Carbon" "Nitrogen" "Oxygen" "Argon"
uv:Ma/FCVacuum/Fractions = 4 0.000124 0.755267 0.231781 0.012828
s:Ma/FCVacuum/State = "Gas"
d:Ma/FCVacuum/Density = 0.00120479 g/cm3
d:Ma/FCVacuum/Temperature = 293 K
d:Ma/FCVacuum/Pressure = 0.01 Pa
d:Ge/Vacuum/RMax = 74.0 mm
d:Ge/Vacuum/HL = 196.0 mm
d:Ge/Vacuum/TransX = 0 mm
d:Ge/Vacuum/TransY = 0 mm
d:Ge/Vacuum/TransZ = -196.1 mm
d:Ge/Vacuum/RotX = 0 deg
d:Ge/Vacuum/RotY = 0 deg
d:Ge/Vacuum/RotZ = 0 deg
sc:Ge/Vacuum/Color = "lightblue"
sc:Ge/Vacuum/DrawingStyle = "Cloud"
s:Ge/Mantle/Type = "TsCylinder"
s:Ge/Mantle/Parent = "FaradayCup"
s:Ge/Mantle/Material = "Steel"
d:Ge/Mantle/RMax = 79.0 mm
d:Ge/Mantle/RMin = 74.0 mm
d:Ge/Mantle/HL = 196.05 mm
d:Ge/Mantle/TransX = 0 mm
d:Ge/Mantle/TransY = 0 mm
d:Ge/Mantle/TransZ = -196.05 mm
d:Ge/Mantle/RotX = 0 deg
d:Ge/Mantle/RotY = 0 deg
d:Ge/Mantle/RotZ = 0 deg
sc:Ge/Mantle/Color = "brown"
sc:Ge/Mantle/DrawingStyle = "FullWireFrame"
s:Ge/GuardRing/Type = "TsCylinder"
s:Ge/GuardRing/Parent = "Vacuum"
s:Ge/GuardRing/Material = "Aluminum"
d:Ge/GuardRing/RMax = 67.2 mm
d:Ge/GuardRing/RMin = 63.5 mm
d:Ge/GuardRing/HL = 77.5 mm
d:Ge/GuardRing/TransX = 0 mm
d:Ge/GuardRing/TransY = 0 mm
d:Ge/GuardRing/TransZ = 86.5 mm
d:Ge/GuardRing/RotX = 0 deg
d:Ge/GuardRing/RotY = 0 deg
d:Ge/GuardRing/RotZ = 0 deg
sc:Ge/GuardRing/Color = "red"
sc:Ge/GuardRing/DrawingStyle = "FullWireFrame"
s:Ge/AbsorberBlock/Type = "Group"
s:Ge/AbsorberBlock/Parent = "Vacuum"
s:Ge/AbsorberBlock/Material = "Brass"
d:Ge/AbsorberBlock/TransX = 0 mm
d:Ge/AbsorberBlock/TransY = 0 mm
d:Ge/AbsorberBlock/TransZ = 0 mm
d:Ge/AbsorberBlock/RotX = 0 deg
d:Ge/AbsorberBlock/RotY = 0 deg
d:Ge/AbsorberBlock/RotZ = 0 deg
s:Ge/AbsorberBlockWalls/Type = "TsCylinder"
s:Ge/AbsorberBlockWalls/Parent = "AbsorberBlock"
s:Ge/AbsorberBlockWalls/Material = "Brass"
d:Ge/AbsorberBlockWalls/RMax = 67.2 mm
d:Ge/AbsorberBlockWalls/RMin = 63.5 mm
d:Ge/AbsorberBlockWalls/HL = 50.0 mm
d:Ge/AbsorberBlockWalls/TransX = 0 mm
d:Ge/AbsorberBlockWalls/TransY = 0 mm
d:Ge/AbsorberBlockWalls/TransZ = -46.0 mm
d:Ge/AbsorberBlockWalls/RotX = 0 deg
d:Ge/AbsorberBlockWalls/RotY = 0 deg
d:Ge/AbsorberBlockWalls/RotZ = 0 deg
sc:Ge/AbsorberBlockWalls/Color = "orange"
sc:Ge/AbsorberBlockWalls/DrawingStyle = "Solid"
s:Ge/AbsorberBlockSolidCollector/Type = "TsCylinder"
s:Ge/AbsorberBlockSolidCollector/Parent = "AbsorberBlock"
s:Ge/AbsorberBlockSolidCollector/Material = "Brass"
d:Ge/AbsorberBlockSolidCollector/RMax = 67.2 mm
d:Ge/AbsorberBlockSolidCollector/HL = 50.0 mm
d:Ge/AbsorberBlockSolidCollector/TransX = 0 mm
d:Ge/AbsorberBlockSolidCollector/TransY = 0 mm
d:Ge/AbsorberBlockSolidCollector/TransZ = -146.00000000000003 mm
d:Ge/AbsorberBlockSolidCollector/RotX = 0 deg
d:Ge/AbsorberBlockSolidCollector/RotY = 0 deg
d:Ge/AbsorberBlockSolidCollector/RotZ = 0 deg
sc:Ge/AbsorberBlockSolidCollector/Color = "orange"
sc:Ge/AbsorberBlockSolidCollector/DrawingStyle = "Solid"
s:Ge/AirAroundCupFront/Type = "TsCylinder"
s:Ge/AirAroundCupFront/Parent = "FaradayCup"
s:Ge/AirAroundCupFront/Material = "G4_AIR"
d:Ge/AirAroundCupFront/RMax = 790.0 mm
d:Ge/AirAroundCupFront/HL = 478.0 mm
d:Ge/AirAroundCupFront/TransX = 0 mm
d:Ge/AirAroundCupFront/TransY = 0 mm
d:Ge/AirAroundCupFront/TransZ = 478.0 mm
d:Ge/AirAroundCupFront/RotX = 0 deg
d:Ge/AirAroundCupFront/RotY = 0 deg
d:Ge/AirAroundCupFront/RotZ = 0 deg
sc:Ge/AirAroundCupFront/Color = "white"
sc:Ge/AirAroundCupFront/DrawingStyle = "WireFrame"
s:Ge/AirAroundCupMid/Type = "TsCylinder"
s:Ge/AirAroundCupMid/Parent = "FaradayCup"
s:Ge/AirAroundCupMid/Material = "G4_AIR"
d:Ge/AirAroundCupMid/RMax = 790.0 mm
d:Ge/AirAroundCupMid/RMin = 79.0 mm
d:Ge/AirAroundCupMid/HL = 196.0 mm
d:Ge/AirAroundCupMid/TransX = 0 mm
d:Ge/AirAroundCupMid/TransY = 0 mm
d:Ge/AirAroundCupMid/TransZ = -196.1 mm
d:Ge/AirAroundCupMid/RotX = 0 deg
d:Ge/AirAroundCupMid/RotY = 0 deg
d:Ge/AirAroundCupMid/RotZ = 0 deg
sc:Ge/AirAroundCupMid/Color = "white"
sc:Ge/AirAroundCupMid/DrawingStyle = "WireFrame"
s:Ge/AirAroundCupBack/Type = "TsCylinder"
s:Ge/AirAroundCupBack/Parent = "FaradayCup"
s:Ge/AirAroundCupBack/Material = "G4_AIR"
d:Ge/AirAroundCupBack/RMax = 790.0 mm
d:Ge/AirAroundCupBack/HL = 478.0 mm
d:Ge/AirAroundCupBack/TransX = 0 mm
d:Ge/AirAroundCupBack/TransY = 0 mm
d:Ge/AirAroundCupBack/TransZ = -870.1 mm
d:Ge/AirAroundCupBack/RotX = 0 deg
d:Ge/AirAroundCupBack/RotY = 0 deg
d:Ge/AirAroundCupBack/RotZ = 0 deg
sc:Ge/AirAroundCupBack/Color = "white"
sc:Ge/AirAroundCupBack/DrawingStyle = "WireFrame"

s:Ge/SourceOrigin/Parent = "FaradayCup"
s:Ge/SourceOrigin/Type = "Group"
d:Ge/SourceOrigin/TransX = 0 cm
d:Ge/SourceOrigin/TransY = 0.0 cm
d:Ge/SourceOrigin/TransZ = 47.8 cm
d:Ge/SourceOrigin/RotX = 0.0 deg
d:Ge/SourceOrigin/RotY = 180.0 deg
d:Ge/SourceOrigin/RotZ = 0.0 deg
s:So/Source/Component = "SourceOrigin"
s:So/Source/BeamParticle = "proton"
s:So/Source/Type = "emittance"
s:So/Source/Distribution = "BiGaussian"
i:So/Source/NumberOfHistoriesInRun = 10
d:So/Source/BeamEnergy = 250 MeV
u:So/Source/BeamEnergySpread = 0.7774
d:So/Source/SigmaX = 0.4586 cm
u:So/Source/SigmaXPrime = 0.0082
u:So/Source/CorrelationX = -0.4341
d:So/Source/SigmaY = 0.3759 cm
u:So/Source/SigmaYPrime = 0.0079
u:So/Source/CorrelationY = -0.3009

s:Ge/SC_VacuumWindowOuterCylinder/Type = "TsCylinder"
s:Ge/SC_VacuumWindowOuterCylinder/Parent = "AirAroundCupFront"
s:Ge/SC_VacuumWindowOuterCylinder/Material = Ge/AirAroundCupFront/Material
d:Ge/SC_VacuumWindowOuterCylinder/RMax = 71.5 mm
d:Ge/SC_VacuumWindowOuterCylinder/HL = 5.0 mm
d:Ge/SC_VacuumWindowOuterCylinder/TransX = 0 mm
d:Ge/SC_VacuumWindowOuterCylinder/TransY = 0 mm
d:Ge/SC_VacuumWindowOuterCylinder/TransZ = -473.0 mm
d:Ge/SC_VacuumWindowOuterCylinder/RotX = 0 deg
d:Ge/SC_VacuumWindowOuterCylinder/RotY = 0 deg
d:Ge/SC_VacuumWindowOuterCylinder/RotZ = 0 deg
sc:Ge/SC_VacuumWindowOuterCylinder/Color = "Maroon"
sc:Ge/SC_VacuumWindowOuterCylinder/DrawingStyle = "FullWireFrame"
s:Ge/SC_VacuumWindowInnerCylinder/Type = "TsCylinder"
s:Ge/SC_VacuumWindowInnerCylinder/Parent = "Vacuum"
s:Ge/SC_VacuumWindowInnerCylinder/Material = Ge/Vacuum/Material
d:Ge/SC_VacuumWindowInnerCylinder/RMax = 71.5 mm
d:Ge/SC_VacuumWindowInnerCylinder/HL = 5.0 mm
d:Ge/SC_VacuumWindowInnerCylinder/TransX = 0 mm
d:Ge/SC_VacuumWindowInnerCylinder/TransY = 0 mm
d:Ge/SC_VacuumWindowInnerCylinder/TransZ = 191.0 mm
d:Ge/SC_VacuumWindowInnerCylinder/RotX = 0 deg
d:Ge/SC_VacuumWindowInnerCylinder/RotY = 0 deg
d:Ge/SC_VacuumWindowInnerCylinder/RotZ = 0 deg
sc:Ge/SC_VacuumWindowInnerCylinder/Color = "Maroon"
sc:Ge/SC_VacuumWindowInnerCylinder/DrawingStyle = "FullWireFrame"
s:Ge/SC_GuardRingInteriorCylinder/Type = "TsCylinder"
s:Ge/SC_GuardRingInteriorCylinder/Parent = "Vacuum"
s:Ge/SC_GuardRingInteriorCylinder/Material = Ge/Vacuum/Material
d:Ge/SC_GuardRingInteriorCylinder/RMax = 63.5 mm
d:Ge/SC_GuardRingInteriorCylinder/HL = 77.5 mm
d:Ge/SC_GuardRingInteriorCylinder/TransX = 0 mm
d:Ge/SC_GuardRingInteriorCylinder/TransY = 0 mm
d:Ge/SC_GuardRingInteriorCylinder/TransZ = 86.5 mm
d:Ge/SC_GuardRingInteriorCylinder/RotX = 0 deg
d:Ge/SC_GuardRingInteriorCylinder/RotY = 0 deg
d:Ge/SC_GuardRingInteriorCylinder/RotZ = 0 deg
sc:Ge/SC_GuardRingInteriorCylinder/Color = "Maroon"
sc:Ge/SC_GuardRingInteriorCylinder/DrawingStyle = "FullWireFrame"
s:Ge/SC_AbsorberBlockWallsInteriorCylinder/Type = "TsCylinder"
s:Ge/SC_AbsorberBlockWallsInteriorCylinder/Parent = "Vacuum"
s:Ge/SC_AbsorberBlockWallsInteriorCylinder/Material = Ge/Vacuum/Material
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/RMax = 63.5 mm
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/HL = 50.0 mm
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/TransX = 0 mm
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/TransY = 0 mm
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/TransZ = -46.0 mm
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/RotX = 0 deg
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/RotY = 0 deg
d:Ge/SC_AbsorberBlockWallsInteriorCylinder/RotZ = 0 deg
sc:Ge/SC_AbsorberBlockWallsInteriorCylinder/Color = "Maroon"
sc:Ge/SC_AbsorberBlockWallsInteriorCylinder/DrawingStyle = "FullWireFrame"
s:Ge/SC_AbsorberBlockSolidCollectorTopLayer/Type = "TsCylinder"
s:Ge/SC_AbsorberBlockSolidCollectorTopLayer/Parent = "AbsorberBlockSolidCollector"
s:Ge/SC_AbsorberBlockSolidCollectorTopLayer/Material = Ge/AbsorberBlockSolidCollector/Material
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/RMax = 67.2 mm
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/HL = 2.0 mm
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/TransX = 0 mm
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/TransY = 0 mm
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/TransZ = 48.0 mm
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/RotX = 0 deg
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/RotY = 0 deg
d:Ge/SC_AbsorberBlockSolidCollectorTopLayer/RotZ = 0 deg
sc:Ge/SC_AbsorberBlockSolidCollectorTopLayer/Color = "Maroon"
sc:Ge/SC_AbsorberBlockSolidCollectorTopLayer/DrawingStyle = "FullWireFrame"

s:Ge/FieldContainer/Field = "ElectroMagneticFieldMap"
s:Ge/FieldContainer/ElectricField3DTable = "./mytests/mapped_electromagnetic/fc_E.csv"
s:Ge/FieldContainer/MagneticField3DTable = "./mytests/mapped_electromagnetic/fc_B.csv"

s:Gr/View/Type = "OpenGL"
b:Gr/View/IncludeAxes = "True"
i:Gr/View/ElectricFieldArrowDensity = 100
i:Gr/View/MagneticFieldArrowDensity = 100

b:Ts/UseQt = "True"
b:Ts/PauseBeforeQuit = "True"