# TOPAS parameter file generated by mc_pce
# File: input.tps

b:Ge/QuitIfOverlapDetected = "true"
b:Ts/PauseBeforeQuit = "false"
i:Ts/RandomSeed = 42
i:Ts/NumberOfThreads = 0
# d:Ph/Default/ForRegion/highprecision/CutForElectron = 1e-03 mm
# d:Ph/Default/ForRegion/highprecision/CutForPositron = 1e-03 mm
# d:Ph/Default/ForRegion/highprecision/CutForProton = 1e-03 mm
# d:Ph/Default/ForRegion/highprecision/CutForGamma = 1e-03 mm
# d:Ph/Default/ForRegion/highprecision/CutForAlpha = 1e-03 mm

d:Ph/Default/ForRegion/microelec/CutForAllParticles = 1 nm
d:Ph/Default/ForRegion/microelec/CutForElectron = 1 nm
d:Ph/Default/ForRegion/microelec/CutForPositron = 1 nm
d:Ph/Default/ForRegion/microelec/CutForGamma = 1 nm

d:Ge/CheckForOverlapsTolerance = 1 nm


b:Ph/Default/PIXE = "true"
b:Ph/Default/Auger = "true"
b:Ph/Default/AugerCascade = "true"
b:Ph/Default/Fluorescence = "true"
i:Ph/Default/EMBins = 220
d:Ph/Default/EMRangeMin = 10.0 eV
d:Ph/Default/LowestElectronEnergy = 5.0 eV
d:Ph/Default/SetProductionCutLowerEdge = 5.0 eV

sv:Ph/Default/Modules = 7 "g4em-microelec" "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-binarycascade" "g4h-elastic_HP" "g4stopping"

b:Ts/UseQt = "true"
s:Gr/View/Type = "OpenGL"
s:Gr/View/ColorBy = "ParticleType"

s:Ge/World/Material = "G4_AIR"
d:Ge/World/HLX = 0.25 m
d:Ge/World/HLY = 0.25 m
d:Ge/World/HLZ = 0.5 m
sc:Ge/World/DrawingStyle = "WireFrame"
sc:Ge/World/Color = "white"
s:Ge/FieldContainer/Type = "TsBox"
s:Ge/FieldContainer/Parent = "World"
s:Ge/FieldContainer/Material = Ge/World/Material
d:Ge/FieldContainer/HLX = Ge/World/HLX m
d:Ge/FieldContainer/HLY = Ge/World/HLY m
d:Ge/FieldContainer/HLZ = Ge/World/HLZ m
d:Ge/FieldContainer/TransX = 0 mm
d:Ge/FieldContainer/TransY = 0 mm
d:Ge/FieldContainer/TransZ = 0 mm
d:Ge/FieldContainer/RotX = 0 deg
d:Ge/FieldContainer/RotY = 0 deg
d:Ge/FieldContainer/RotZ = 0 deg
sc:Ge/FieldContainer/Color = "grey220"
sc:Ge/FieldContainer/DrawingStyle = "WireFrame"

s:Ge/VacuumWindowGroup/Type = "Group"
s:Ge/VacuumWindowGroup/Parent = "FieldContainer"
s:Ge/VacuumWindowGroup/Material = "G4_Al"
d:Ge/VacuumWindowGroup/TransX = 0 mm
d:Ge/VacuumWindowGroup/TransY = 0 mm
d:Ge/VacuumWindowGroup/TransZ = -0.05 mm
d:Ge/VacuumWindowGroup/RotX = 0 deg
d:Ge/VacuumWindowGroup/RotY = 0 deg
d:Ge/VacuumWindowGroup/RotZ = 0 deg
s:Ge/VacuumWindow/Type = "TsCylinder"
s:Ge/VacuumWindow/Parent = "VacuumWindowGroup"
s:Ge/VacuumWindow/Material = "G4_Al"
s:Ge/VacuumWindow/AssignToRegionNamed = "highprecision"
d:Ge/VacuumWindow/RMax = 71.5 mm
d:Ge/VacuumWindow/HL = 0.04995 mm
d:Ge/VacuumWindow/TransX = 0 mm
d:Ge/VacuumWindow/TransY = 0 mm
d:Ge/VacuumWindow/TransZ = 5e-05 mm
d:Ge/VacuumWindow/RotX = 0 deg
d:Ge/VacuumWindow/RotY = 0 deg
d:Ge/VacuumWindow/RotZ = 0 deg
sc:Ge/VacuumWindow/Color = "grey220"
sc:Ge/VacuumWindow/DrawingStyle = "Solid"
s:Ge/VacuumWindowMicroelecLayer/Type = "TsCylinder"
s:Ge/VacuumWindowMicroelecLayer/Parent = "VacuumWindowGroup"
s:Ge/VacuumWindowMicroelecLayer/Material = "G4_Al"
s:Ge/VacuumWindowMicroelecLayer/AssignToRegionNamed = "microelec"
d:Ge/VacuumWindowMicroelecLayer/RMax = 71.5 mm
d:Ge/VacuumWindowMicroelecLayer/HL = 5e-05 mm
d:Ge/VacuumWindowMicroelecLayer/TransX = 0 mm
d:Ge/VacuumWindowMicroelecLayer/TransY = 0 mm
d:Ge/VacuumWindowMicroelecLayer/TransZ = -0.04995 mm
d:Ge/VacuumWindowMicroelecLayer/RotX = 0 deg
d:Ge/VacuumWindowMicroelecLayer/RotY = 0 deg
d:Ge/VacuumWindowMicroelecLayer/RotZ = 0 deg
sc:Ge/VacuumWindowMicroelecLayer/Color = "grey220"
sc:Ge/VacuumWindowMicroelecLayer/DrawingStyle = "Solid"

s:Ge/Vacuum/Type = "TsCylinder"
s:Ge/Vacuum/Parent = "FieldContainer"
s:Ge/Vacuum/Material = "FCVacuum"
s:Ge/Vacuum/AssignToRegionNamed = "highprecision"
sv:Ma/FCVacuum/Components = 4 "Carbon" "Nitrogen" "Oxygen" "Argon"
uv:Ma/FCVacuum/Fractions = 4 0.000124 0.755267 0.231781 0.012828
s:Ma/FCVacuum/State = "Gas"
d:Ma/FCVacuum/Density = 1.19e-10 g/cm3
d:Ma/FCVacuum/Temperature = 293 K
d:Ma/FCVacuum/Pressure = 0.01 Pa
d:Ge/Vacuum/RMax = 74.0 mm
d:Ge/Vacuum/HL = 196.0 mm
d:Ge/Vacuum/TransX = 0 mm
d:Ge/Vacuum/TransY = 0 mm
d:Ge/Vacuum/TransZ = -196.1 mm
d:Ge/Vacuum/RotX = 0 deg
d:Ge/Vacuum/RotY = 0 deg
d:Ge/Vacuum/RotZ = 0 deg
sc:Ge/Vacuum/Color = "lightblue"
sc:Ge/Vacuum/DrawingStyle = "WireFrame"

s:Ge/Mantle/Type = "TsCylinder"
s:Ge/Mantle/Parent = "FieldContainer"
s:Ge/Mantle/Material = "Steel"
s:Ge/Mantle/AssignToRegionNamed = "highprecision"
d:Ge/Mantle/RMax = 79.0 mm
d:Ge/Mantle/RMin = 74.0 mm
d:Ge/Mantle/HL = 196.05 mm
d:Ge/Mantle/TransX = 0 mm
d:Ge/Mantle/TransY = 0 mm
d:Ge/Mantle/TransZ = -196.05 mm
d:Ge/Mantle/RotX = 0 deg
d:Ge/Mantle/RotY = 0 deg
d:Ge/Mantle/RotZ = 0 deg
sc:Ge/Mantle/Color = "brown"
sc:Ge/Mantle/DrawingStyle = "FullWireFrame"

s:Ge/GuardRing/Type = "TsCylinder"
s:Ge/GuardRing/Parent = "Vacuum"
s:Ge/GuardRing/Material = "Aluminum"
s:Ge/GuardRing/AssignToRegionNamed = "highprecision"
d:Ge/GuardRing/RMax = 67.2 mm
d:Ge/GuardRing/RMin = 63.5 mm
d:Ge/GuardRing/HL = 77.5 mm
d:Ge/GuardRing/TransX = 0 mm
d:Ge/GuardRing/TransY = 0 mm
d:Ge/GuardRing/TransZ = 86.5 mm
d:Ge/GuardRing/RotX = 0 deg
d:Ge/GuardRing/RotY = 0 deg
d:Ge/GuardRing/RotZ = 0 deg
sc:Ge/GuardRing/Color = "red"
sc:Ge/GuardRing/DrawingStyle = "FullWireFrame"

s:Ge/AbsorberBlockWalls/Type = "TsCylinder"
s:Ge/AbsorberBlockWalls/Parent = "Vacuum"
s:Ge/AbsorberBlockWalls/Material = "Brass"
s:Ge/AbsorberBlockWalls/AssignToRegionNamed = "highprecision"
d:Ge/AbsorberBlockWalls/RMax = 67.2 mm
d:Ge/AbsorberBlockWalls/RMin = 63.5 mm
d:Ge/AbsorberBlockWalls/HL = 50.0 mm
d:Ge/AbsorberBlockWalls/TransX = 0 mm
d:Ge/AbsorberBlockWalls/TransY = 0 mm
d:Ge/AbsorberBlockWalls/TransZ = -46.0 mm
d:Ge/AbsorberBlockWalls/RotX = 0 deg
d:Ge/AbsorberBlockWalls/RotY = 0 deg
d:Ge/AbsorberBlockWalls/RotZ = 0 deg
sc:Ge/AbsorberBlockWalls/Color = "orange"
sc:Ge/AbsorberBlockWalls/DrawingStyle = "Solid"

s:Ge/AbsorberBlockSolidCollector/Type = "Group"
s:Ge/AbsorberBlockSolidCollector/Parent = "Vacuum"
s:Ge/AbsorberBlockSolidCollector/Material = "Brass"
d:Ge/AbsorberBlockSolidCollector/TransX = 0 mm
d:Ge/AbsorberBlockSolidCollector/TransY = 0 mm
d:Ge/AbsorberBlockSolidCollector/TransZ = -146 mm
d:Ge/AbsorberBlockSolidCollector/RotX = 0 deg
d:Ge/AbsorberBlockSolidCollector/RotY = 0 deg
d:Ge/AbsorberBlockSolidCollector/RotZ = 0 deg
sc:Ge/AbsorberBlockSolidCollector/Color = "orange"

sc:Ge/AbsorberBlockSolidCollector/DrawingStyle = "WireFrame"
s:Ge/AbsorberBlockSolidCollectorTopLayer/Type = "TsCylinder"
s:Ge/AbsorberBlockSolidCollectorTopLayer/Parent = "AbsorberBlockSolidCollector"
s:Ge/AbsorberBlockSolidCollectorTopLayer/Material = "G4_Cu"
d:Ge/AbsorberBlockSolidCollectorTopLayer/RMax = 67.2 mm
d:Ge/AbsorberBlockSolidCollectorTopLayer/HL = 5e-3 mm
d:Ge/AbsorberBlockSolidCollectorTopLayer/TransX = 0 mm
d:Ge/AbsorberBlockSolidCollectorTopLayer/TransY = 0 mm
d:Ge/AbsorberBlockSolidCollectorTopLayer/TransZ = 49.995 mm
d:Ge/AbsorberBlockSolidCollectorTopLayer/RotX = 0 deg
d:Ge/AbsorberBlockSolidCollectorTopLayer/RotY = 0 deg
d:Ge/AbsorberBlockSolidCollectorTopLayer/RotZ = 0 deg
sc:Ge/AbsorberBlockSolidCollectorTopLayer/Color = "orange"
sc:Ge/AbsorberBlockSolidCollectorTopLayer/DrawingStyle = "Solid"

s:Ge/AbsorberBlockSolidCollectorTopLayer/AssignToRegionNamed = "microelec"

s:Ge/AbsorberBlockSolidCollectorBottomLayer/Type = "TsCylinder"
s:Ge/AbsorberBlockSolidCollectorBottomLayer/Parent = "AbsorberBlockSolidCollector"
s:Ge/AbsorberBlockSolidCollectorBottomLayer/Material = "Brass"
d:Ge/AbsorberBlockSolidCollectorBottomLayer/RMax = 67.2 mm
d:Ge/AbsorberBlockSolidCollectorBottomLayer/HL = 49.995 mm
d:Ge/AbsorberBlockSolidCollectorBottomLayer/TransX = 0 mm
d:Ge/AbsorberBlockSolidCollectorBottomLayer/TransY = 0 mm
d:Ge/AbsorberBlockSolidCollectorBottomLayer/TransZ = -5e-3 mm
d:Ge/AbsorberBlockSolidCollectorBottomLayer/RotX = 0 deg
d:Ge/AbsorberBlockSolidCollectorBottomLayer/RotY = 0 deg
d:Ge/AbsorberBlockSolidCollectorBottomLayer/RotZ = 0 deg
sc:Ge/AbsorberBlockSolidCollectorBottomLayer/Color = "orange"
sc:Ge/AbsorberBlockSolidCollectorBottomLayer/DrawingStyle = "Solid"

s:Ge/AbsorberBlockSolidCollectorBottomLayer/AssignToRegionNamed = "highprecision"

# s:Ge/FieldContainer/Field = "ElectricFieldMap"
# s:Ge/FieldContainer/ElectricField3DTable = "/asmnobackup/user/balles_m/FaradayCup/data/input/field_tables/electric/csv/EField_-1000V.csv"

i:Gr/View/ElectricFieldArrowDensity = 10


s:Ge/SourceOrigin/Parent = "FieldContainer"
s:Ge/SourceOrigin/Type = "Group"
d:Ge/SourceOrigin/TransX = 0.0 mm
d:Ge/SourceOrigin/TransY = 0.0 mm
d:Ge/SourceOrigin/TransZ = 478.0 mm
d:Ge/SourceOrigin/RotX = 0.0 deg
d:Ge/SourceOrigin/RotY = 180.0 deg
d:Ge/SourceOrigin/RotZ = 0.0 deg
s:So/Source/Component = "SourceOrigin"
s:So/Source/BeamParticle = "proton"
s:So/Source/Type = "emittance"
s:So/Source/Distribution = "bigaussian"
d:So/Source/BeamEnergy = 70.939 MeV
u:So/Source/BeamEnergySpread = 0.777402
d:So/Source/SigmaX = 4.71598 mm
u:So/Source/SigmaXPrime = 0.0082
d:So/Source/SigmaY = 3.91972 mm
u:So/Source/SigmaYPrime = 0.0079
u:So/Source/CorrelationX = -0.095231
u:So/Source/CorrelationY = 0.118743
i:So/Source/NumberOfHistoriesInRun = 2
